#!/usr/bin/env bash
# lib/common.sh -- shared OS bootstrap functions for k3s server and agent nodes.
# Pure bash -- no Terraform interpolation. Sourced by prepending to cloud-init scripts.
# Variables (K3S_VERSION, VAULT_SECRET_ID_K3S_TOKEN, etc.) are exported by
# the Terraform-rendered vars header (server-vars.sh.tpl / agent-vars.sh.tpl).
# shellcheck disable=SC2154

# -- OS bootstrap --------------------------------------------------------------

# Wait for apt/dpkg locks so our apt calls never race with apt-daily or
# unattended-upgrades that Ubuntu starts automatically on first boot.
wait_apt_lock() {
  local lockfiles=(
    /var/lib/dpkg/lock-frontend
    /var/lib/dpkg/lock
    /var/cache/apt/archives/lock
    /var/lib/apt/lists/lock
  )
  local waited=0
  while fuser "${lockfiles[@]}" &>/dev/null 2>&1; do
    if (( waited == 0 )); then
      echo "Waiting for apt/dpkg lock to be released..."
    fi
    sleep 5
    (( waited += 5 ))
    if (( waited >= 300 )); then
      echo "Apt lock held for 5 minutes -- killing apt-daily and continuing."
      systemctl kill --kill-who=all apt-daily.service apt-daily-upgrade.service 2>/dev/null || true
      sleep 3
      break
    fi
  done
}

# Write a cluster-wide shared SSH host key so that all nodes behind the NLB
# present the same fingerprint (eliminates "REMOTE HOST IDENTIFICATION HAS CHANGED").
# The key is generated by Terraform and distributed via cloud-init as base64.
setup_shared_ssh_host_key() {
  echo "${SSH_HOST_KEY_PRIVATE_B64}" | base64 -d > /etc/ssh/ssh_host_ed25519_key
  printf '%s\n' "${SSH_HOST_KEY_PUBLIC}"          > /etc/ssh/ssh_host_ed25519_key.pub
  chmod 600 /etc/ssh/ssh_host_ed25519_key
  chmod 644 /etc/ssh/ssh_host_ed25519_key.pub
  systemctl restart ssh
}

bootstrap() {
  /usr/sbin/netfilter-persistent stop  || true
  /usr/sbin/netfilter-persistent flush || true
  systemctl stop    netfilter-persistent.service || true
  systemctl disable netfilter-persistent.service || true

  # Stop Ubuntu's apt-daily timer so it doesn't race with our apt calls.
  # configure_unattended_upgrades() will re-enable it after we're done.
  systemctl stop apt-daily.service apt-daily-upgrade.service 2>/dev/null || true
  wait_apt_lock

  # OCI instances only have IPv4 routes; force apt to avoid IPv6 mirror timeouts
  echo 'Acquire::ForceIPv4 "true";' > /etc/apt/apt.conf.d/99force-ipv4

  export DEBIAN_FRONTEND=noninteractive
  # Tolerate partial mirror failures (transient OCI regional mirror issues)
  apt-get update -q || apt-get update -q || true
  apt-get install -y -q --no-install-recommends \
    software-properties-common jq curl python3 \
    open-iscsi nfs-common util-linux
  # Hold the oracle kernel packages so that apt-get upgrade or unattended-upgrades
  # cannot install a newer kernel during cloud-init. A new kernel would become the
  # grub default and the machine would reboot into it on the next boot, potentially
  # hitting regressions (e.g. 6.17.0-1010 boot loop on OCI A1.Flex).
  # kured + system-upgrade-controller manage planned kernel upgrades.
  apt-mark hold linux-oracle linux-image-oracle linux-headers-oracle || true
  # Security and package upgrades are deferred to unattended-upgrades on its
  # daily schedule so that the cluster is healthy before any OS changes land.
  # Never run apt-get upgrade here: it would install the held kernel and trigger
  # a reboot into a potentially broken kernel, causing a boot loop.
  apt-get clean
  rm -rf /var/lib/apt/lists/*

  # Cap journal size to protect the boot volume.
  # Use a drop-in so this is idempotent on repeated cloud-init runs.
  mkdir -p /etc/systemd/journald.conf.d
  cat > /etc/systemd/journald.conf.d/10-k3s-size-limit.conf << 'JEOF'
[Journal]
SystemMaxUse=100M
SystemMaxFileSize=100M
JEOF
  systemctl restart systemd-journald

  setup_shared_ssh_host_key
}

# -- Unattended upgrades -------------------------------------------------------

configure_unattended_upgrades() {
  export DEBIAN_FRONTEND=noninteractive
  wait_apt_lock
  # Note: apt-get update already ran in bootstrap(); this second run ensures
  # unattended-upgrades and needrestart are always installable even on slow mirrors.
  apt-get install -y -q --no-install-recommends unattended-upgrades needrestart
  apt-get clean
  rm -rf /var/lib/apt/lists/*

  cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'UUEOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};
Unattended-Upgrade::Package-Blacklist {};
Unattended-Upgrade::DevRelease "false";
Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
// kured handles reboots -- never auto-reboot here
Unattended-Upgrade::Automatic-Reboot "false";
UUEOF

  cat > /etc/apt/apt.conf.d/20auto-upgrades << 'UUEOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";
UUEOF

  # needrestart: automatically restart affected userspace services after package
  # updates (mode 'a' = automatic). CVE patches take effect immediately for
  # running daemons without waiting for the kured reboot window.
  # k3s is excluded -- its lifecycle is managed by the cluster upgrade controller.
  mkdir -p /etc/needrestart/conf.d
  cat > /etc/needrestart/conf.d/99-k3s.conf << 'NREOF'
$nrconf{restart} = 'a';
$nrconf{blacklist_rc} = [qr(^k3s)];
NREOF

  # Security-only origins -- used by apt-security-upgrade.timer (daily).
  # Non-security origins are handled by apt-daily-upgrade (Tue/Wed/Thu).
  cat > /etc/apt/apt.conf.d/52security-only.conf << 'SECEOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};
SECEOF

  # Daily security-only upgrade service + timer at 00:30 UTC (+/-30 min jitter).
  cat > /etc/systemd/system/apt-security-upgrade.service << 'SVCEOF'
[Unit]
Description=Daily security-only unattended upgrades
Documentation=man:unattended-upgrade(8)
After=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/bin/unattended-upgrade --apt-conf /etc/apt/apt.conf.d/52security-only.conf
SVCEOF

  cat > /etc/systemd/system/apt-security-upgrade.timer << 'TMREOF'
[Unit]
Description=Run security-only unattended upgrades daily

[Timer]
OnCalendar=*-*-* 00:30:00 UTC
RandomizedDelaySec=1800
Persistent=true

[Install]
WantedBy=timers.target
TMREOF

  # Non-security upgrades: Tue/Wed/Thu at 01:00 UTC (+/-10 min jitter).
  mkdir -p /etc/systemd/system/apt-daily-upgrade.timer.d
  cat > /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf << 'TIMEREOF'
[Timer]
OnCalendar=
OnCalendar=Tue,Wed,Thu *-*-* 01:00:00 UTC
RandomizedDelaySec=600
Persistent=true
TIMEREOF

  systemctl daemon-reload
  systemctl enable --now apt-security-upgrade.timer
  systemctl restart apt-daily-upgrade.timer

  systemctl enable --now unattended-upgrades
}

# -- Longhorn prerequisites ----------------------------------------------------

configure_longhorn_prereqs() {
  systemctl enable --now iscsid.service
  modprobe nfs || true
}

# -- OCI CLI -------------------------------------------------------------------
# Always installed on server nodes (required for first-server election via
# instance_principal auth). Installed on agent nodes only when Vault is enabled.

install_oci_cli() {
  if /root/bin/oci --version &>/dev/null 2>&1; then
    echo "OCI CLI already installed, skipping."
    return 0
  fi
  bash -c "$(curl -sfL https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" \
    -- --accept-all-defaults
  # Suppress announcements so they never pollute stdout of subsequent oci commands
  # (announcements on stdout break pipes to jq / base64). Use python3 to set the
  # key idempotently in [OCI_CLI_SETTINGS] rather than blindly appending.
  python3 - <<'RCEOF'
import configparser, os
rc = os.path.expanduser('~/.oci/oci_cli_rc')
os.makedirs(os.path.dirname(rc), exist_ok=True)
cfg = configparser.ConfigParser()
cfg.read(rc)
if not cfg.has_section('OCI_CLI_SETTINGS'):
    cfg.add_section('OCI_CLI_SETTINGS')
cfg.set('OCI_CLI_SETTINGS', 'suppress_feedback', 'True')
with open(rc, 'w') as f:
    cfg.write(f)
RCEOF
}

# -- Helm ----------------------------------------------------------------------

install_helm() {
  command -v helm &>/dev/null && return 0
  curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
}

# -- Network helpers -----------------------------------------------------------
# Resolve node IP and flannel interface from K3S_SUBNET when a specific subnet
# CIDR is provided. Sets LOCAL_IP and FLANNEL_IFACE in the caller's scope.
# Used by both server and agent install functions.

resolve_flannel_params() {
  if [[ "${K3S_SUBNET}" != "default_route_table" ]]; then
    export LOCAL_IP
    export FLANNEL_IFACE
    LOCAL_IP=$(ip -4 route ls "${K3S_SUBNET}" | grep -Po '(?<=src )(\S+)')
    FLANNEL_IFACE=$(ip -4 route ls "${K3S_SUBNET}" | grep -Po '(?<=dev )(\S+)')
    if [[ -z "${LOCAL_IP}" || -z "${FLANNEL_IFACE}" ]]; then
      echo "ERROR: resolve_flannel_params: could not determine LOCAL_IP or FLANNEL_IFACE from subnet '${K3S_SUBNET}'."
      echo "  'ip -4 route ls ${K3S_SUBNET}' returned no usable result."
      echo "  Check that K3S_SUBNET matches an interface route on this node."
      exit 1
    fi
  fi
}
