#!/usr/bin/env bash
# lib/common.sh -- shared OS-agnostic bootstrap helpers for k3s server and agent nodes.
# Pure bash -- no Terraform interpolation. Sourced by prepending to cloud-init scripts.
# Variables (K3S_VERSION, VAULT_SECRET_ID_K3S_TOKEN, etc.) are exported by
# the Terraform-rendered vars header (server-vars.sh.tpl / agent-vars.sh.tpl).
# OS-specific bootstrap (bootstrap() and configure_unattended_upgrades()) is provided
# by bootstrap-ubuntu.sh or bootstrap-opensuse.sh, prepended before this file by data.tf.
# shellcheck disable=SC2154

# Write a cluster-wide shared SSH host key so that all nodes behind the NLB
# present the same fingerprint (eliminates "REMOTE HOST IDENTIFICATION HAS CHANGED").
# The key is generated by Terraform and distributed via cloud-init as base64.
setup_shared_ssh_host_key() {
  # Decode to a temp file first; a partial decode (malformed base64) would
  # write a truncated key and silently break SSH on the next connection.
  local tmp_key
  tmp_key=$(mktemp)
  if ! echo "${SSH_HOST_KEY_PRIVATE_B64}" | base64 -d > "${tmp_key}"; then
    rm -f "${tmp_key}"
    echo "ERROR: base64 decode of SSH_HOST_KEY_PRIVATE_B64 failed — shared SSH host key not installed."
    exit 1
  fi
  mv "${tmp_key}" /etc/ssh/ssh_host_ed25519_key
  printf '%s\n' "${SSH_HOST_KEY_PUBLIC}"          > /etc/ssh/ssh_host_ed25519_key.pub
  chmod 600 /etc/ssh/ssh_host_ed25519_key
  chmod 644 /etc/ssh/ssh_host_ed25519_key.pub
  # Service name is "ssh" on Ubuntu/Debian and "sshd" on openSUSE/RHEL.
  systemctl restart ssh 2>/dev/null || systemctl restart sshd
}

# -- Longhorn prerequisites ----------------------------------------------------

configure_longhorn_prereqs() {
  systemctl enable --now iscsid.service
  modprobe nfs || true
}

# -- OCI CLI -------------------------------------------------------------------
# Always installed on server nodes (required for first-server election via
# instance_principal auth). Installed on agent nodes only when Vault is enabled.

install_oci_cli() {
  if /root/bin/oci --version &>/dev/null 2>&1; then
    echo "OCI CLI already installed, skipping."
    return 0
  fi
  bash -c "$(curl -sfL https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" \
    -- --accept-all-defaults
  # Suppress announcements so they never pollute stdout of subsequent oci commands
  # (announcements on stdout break pipes to jq / base64). Use python3 to set the
  # key idempotently in [OCI_CLI_SETTINGS] rather than blindly appending.
  python3 - <<'RCEOF'
import configparser, os
rc = os.path.expanduser('~/.oci/oci_cli_rc')
os.makedirs(os.path.dirname(rc), exist_ok=True)
cfg = configparser.ConfigParser()
cfg.read(rc)
if not cfg.has_section('OCI_CLI_SETTINGS'):
    cfg.add_section('OCI_CLI_SETTINGS')
cfg.set('OCI_CLI_SETTINGS', 'suppress_feedback', 'True')
with open(rc, 'w') as f:
    cfg.write(f)
RCEOF
}

# -- Helm ----------------------------------------------------------------------

install_helm() {
  command -v helm &>/dev/null && return 0
  curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash || {
    echo "ERROR: Helm install failed."
    return 1
  }
}

# -- Network helpers -----------------------------------------------------------
# Resolve node IP and flannel interface from K3S_SUBNET when a specific subnet
# CIDR is provided. Sets LOCAL_IP and FLANNEL_IFACE in the caller's scope.
# Used by both server and agent install functions.

resolve_flannel_params() {
  if [[ "${K3S_SUBNET}" != "default_route_table" ]]; then
    export LOCAL_IP
    export FLANNEL_IFACE
    LOCAL_IP=$(ip -4 route ls "${K3S_SUBNET}" | grep -Po '(?<=src )(\S+)')
    FLANNEL_IFACE=$(ip -4 route ls "${K3S_SUBNET}" | grep -Po '(?<=dev )(\S+)')
    if [[ -z "${LOCAL_IP}" || -z "${FLANNEL_IFACE}" ]]; then
      echo "ERROR: resolve_flannel_params: could not determine LOCAL_IP or FLANNEL_IFACE from subnet '${K3S_SUBNET}'."
      echo "  'ip -4 route ls ${K3S_SUBNET}' returned no usable result."
      echo "  Check that K3S_SUBNET matches an interface route on this node."
      exit 1
    fi
  fi
}

# setup_etcd_snapshot_upload
# Installs a cron job that takes a k3s etcd snapshot and uploads it to OCI Object
# Storage every 6 hours using OCI CLI instance_principal auth (no S3 credentials).
# Requires ETCD_SNAPSHOT_BUCKET and OCI_OBJECT_NAMESPACE to be non-empty.
# Only called on the first (elected) server node.

setup_etcd_snapshot_upload() {
  if [[ "${ENABLE_ETCD_SNAPSHOTS:-false}" != "true" ]] \
     || [[ -z "${ETCD_SNAPSHOT_BUCKET:-}" ]] \
     || [[ -z "${OCI_OBJECT_NAMESPACE:-}" ]]; then
    echo "INFO: etcd snapshot upload not configured (ENABLE_ETCD_SNAPSHOTS=${ENABLE_ETCD_SNAPSHOTS:-false})."
    return 0
  fi

  local upload_script="/usr/local/bin/etcd-snapshot-upload.sh"
  local retain="${ETCD_SNAPSHOT_RETENTION:-5}"

  cat > "${upload_script}" << 'ETCD_SCRIPT'
#!/usr/bin/env bash
# Cron-managed etcd snapshot upload to OCI Object Storage via instance_principal.
# Installed by cloud-init; edit /etc/cron.d/etcd-snapshot-upload to reschedule.
set -euo pipefail

export OCI_CLI_AUTH=instance_principal
export PATH="/root/bin:$PATH"

SNAPSHOT_DIR="/var/lib/rancher/k3s/server/db/snapshots"
BUCKET="__ETCD_BUCKET__"
NAMESPACE="__OCI_NAMESPACE__"
CLUSTER="__CLUSTER_NAME__"
RETAIN=__RETAIN__

SNAPSHOT_NAME="etcd-snapshot-${CLUSTER}-$(date -u +%Y%m%d-%H%M%S)"
echo "[$(date -u)] Creating etcd snapshot: ${SNAPSHOT_NAME}"

k3s etcd-snapshot save --name "${SNAPSHOT_NAME}" 2>&1 || {
  echo "[$(date -u)] ERROR: k3s etcd-snapshot save failed." >&2
  exit 1
}

SNAPSHOT_FILE=$(find "${SNAPSHOT_DIR}" -name "${SNAPSHOT_NAME}*" -type f | head -1)
if [[ -z "${SNAPSHOT_FILE}" ]]; then
  echo "[$(date -u)] ERROR: Snapshot file not found for ${SNAPSHOT_NAME}" >&2
  exit 1
fi

echo "[$(date -u)] Uploading $(basename "${SNAPSHOT_FILE}") to oci://${BUCKET}/etcd-snapshots/${CLUSTER}/"
oci os object put \
  --namespace "${NAMESPACE}" \
  --bucket-name "${BUCKET}" \
  --name "etcd-snapshots/${CLUSTER}/$(basename "${SNAPSHOT_FILE}")" \
  --file "${SNAPSHOT_FILE}" \
  --no-multipart

echo "[$(date -u)] Pruning old snapshots (keeping last ${RETAIN})..."
oci os object list \
  --namespace "${NAMESPACE}" \
  --bucket-name "${BUCKET}" \
  --prefix "etcd-snapshots/${CLUSTER}/" \
  --all \
  --query "sort_by(data, &\"time-created\")[:-${RETAIN}].name" \
  --raw-output 2>/dev/null \
  | python3 -c "import sys,json; [print(x) for x in (json.load(sys.stdin) or [])]" 2>/dev/null \
  | while IFS= read -r old_obj; do
      [[ -z "${old_obj}" ]] && continue
      echo "[$(date -u)]   Deleting: ${old_obj}"
      oci os object delete \
        --namespace "${NAMESPACE}" \
        --bucket-name "${BUCKET}" \
        --object-name "${old_obj}" \
        --force 2>/dev/null || true
    done

echo "[$(date -u)] etcd snapshot upload complete."
ETCD_SCRIPT

  # Substitute placeholders with actual values
  sed -i "s|__ETCD_BUCKET__|${ETCD_SNAPSHOT_BUCKET}|g" "${upload_script}"
  sed -i "s|__OCI_NAMESPACE__|${OCI_OBJECT_NAMESPACE}|g" "${upload_script}"
  sed -i "s|__CLUSTER_NAME__|${CLUSTER_NAME}|g" "${upload_script}"
  sed -i "s|__RETAIN__|${retain}|g" "${upload_script}"
  chmod +x "${upload_script}"

  # Schedule: every 6 hours at minute 0
  echo "0 */6 * * * root ${upload_script} >> /var/log/etcd-snapshot-upload.log 2>&1" \
    > /etc/cron.d/etcd-snapshot-upload

  # Run initial snapshot immediately to verify the path works
  echo "Running initial etcd snapshot upload..."
  "${upload_script}" || echo "WARNING: Initial snapshot upload failed — check /var/log/etcd-snapshot-upload.log"

  echo "etcd snapshot cron job installed (every 6 hours; retaining last ${retain} snapshots)."
}


# Retries up to 20 times (30s gap = ~10 min) to handle IAM dynamic-group
# propagation delay on newly launched instances.
# Diagnostic output goes to stderr so it appears in the log even when this
# function is called inside a $() command substitution (which captures stdout).
fetch_from_vault() {
  local secret_id="$1"
  local max_attempts=20
  local delay=30
  local attempt=0
  local raw_value
  while [[ $attempt -lt $max_attempts ]]; do
    attempt=$((attempt + 1))
    if raw_value=$(oci secrets secret-bundle get \
      --secret-id "${secret_id}" \
      --query 'data."secret-bundle-content".content' \
      --raw-output 2>&1); then
      # Validate and decode; a malformed response would silently pass garbage downstream.
      local decoded
      if ! decoded=$(echo "${raw_value}" | base64 -d 2>/dev/null) || [[ -z "${decoded}" ]]; then
        echo "Vault fetch attempt ${attempt}/${max_attempts}: base64 decode failed or empty — retrying..." >&2
        sleep "${delay}"
        continue
      fi
      echo "${decoded}"
      return 0
    fi
    echo "Vault fetch attempt ${attempt}/${max_attempts} failed, retrying in ${delay}s..." >&2
    sleep "${delay}"
  done
  echo "ERROR: Failed to fetch secret '${secret_id}' from OCI Vault after ${max_attempts} attempts." >&2
  return 1
}

# resolve_k3s_token [needs_oci_cli]
# Fetches K3S_TOKEN from OCI Vault with plaintext fallback, then exports it.
# Pass "needs_oci_cli" on agent nodes where OCI CLI is not yet installed
# (servers already install it unconditionally via install_oci_cli()).

resolve_k3s_token() {
  if [[ "${1:-}" == "needs_oci_cli" ]]; then
    export OCI_CLI_AUTH=instance_principal
    export PATH="/root/bin:$PATH"
    install_oci_cli
  fi

  if [[ -n "${VAULT_SECRET_ID_K3S_TOKEN}" ]]; then
    echo "Fetching k3s token from OCI Vault..."
    if K3S_TOKEN=$(fetch_from_vault "${VAULT_SECRET_ID_K3S_TOKEN}"); then
      echo "Vault fetch successful."
    else
      echo "WARNING: Vault fetch failed — falling back to plaintext token from user-data." >&2
      K3S_TOKEN="${K3S_TOKEN_PLAIN}"
      [[ -z "${K3S_TOKEN}" ]] && { echo "ERROR: K3S_TOKEN_PLAIN is empty — cannot continue." >&2; exit 1; }
    fi
  else
    K3S_TOKEN="${K3S_TOKEN_PLAIN}"
  fi
  export K3S_TOKEN
}
