#!/usr/bin/env bash
# lib/common.sh -- shared OS-agnostic bootstrap helpers for k3s server and agent nodes.
# Pure bash -- no Terraform interpolation. Sourced by prepending to cloud-init scripts.
# Variables (K3S_VERSION, VAULT_SECRET_ID_K3S_TOKEN, etc.) are exported by
# the Terraform-rendered vars header (server-vars.sh.tpl / agent-vars.sh.tpl).
# OS-specific bootstrap (bootstrap() and configure_unattended_upgrades()) is provided
# by bootstrap-ubuntu.sh or bootstrap-opensuse.sh, prepended before this file by data.tf.
# shellcheck disable=SC2154

# Write a cluster-wide shared SSH host key so that all nodes behind the NLB
# present the same fingerprint (eliminates "REMOTE HOST IDENTIFICATION HAS CHANGED").
# The key is generated by Terraform and distributed via cloud-init as base64.
setup_shared_ssh_host_key() {
  echo "${SSH_HOST_KEY_PRIVATE_B64}" | base64 -d > /etc/ssh/ssh_host_ed25519_key
  printf '%s\n' "${SSH_HOST_KEY_PUBLIC}"          > /etc/ssh/ssh_host_ed25519_key.pub
  chmod 600 /etc/ssh/ssh_host_ed25519_key
  chmod 644 /etc/ssh/ssh_host_ed25519_key.pub
  # Service name is "ssh" on Ubuntu/Debian and "sshd" on openSUSE/RHEL.
  systemctl restart ssh 2>/dev/null || systemctl restart sshd
}

# -- Longhorn prerequisites ----------------------------------------------------

configure_longhorn_prereqs() {
  systemctl enable --now iscsid.service
  modprobe nfs || true
}

# -- OCI CLI -------------------------------------------------------------------
# Always installed on server nodes (required for first-server election via
# instance_principal auth). Installed on agent nodes only when Vault is enabled.

install_oci_cli() {
  if /root/bin/oci --version &>/dev/null 2>&1; then
    echo "OCI CLI already installed, skipping."
    return 0
  fi
  bash -c "$(curl -sfL https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" \
    -- --accept-all-defaults
  # Suppress announcements so they never pollute stdout of subsequent oci commands
  # (announcements on stdout break pipes to jq / base64). Use python3 to set the
  # key idempotently in [OCI_CLI_SETTINGS] rather than blindly appending.
  python3 - <<'RCEOF'
import configparser, os
rc = os.path.expanduser('~/.oci/oci_cli_rc')
os.makedirs(os.path.dirname(rc), exist_ok=True)
cfg = configparser.ConfigParser()
cfg.read(rc)
if not cfg.has_section('OCI_CLI_SETTINGS'):
    cfg.add_section('OCI_CLI_SETTINGS')
cfg.set('OCI_CLI_SETTINGS', 'suppress_feedback', 'True')
with open(rc, 'w') as f:
    cfg.write(f)
RCEOF
}

# -- Helm ----------------------------------------------------------------------

install_helm() {
  command -v helm &>/dev/null && return 0
  curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
}

# -- Network helpers -----------------------------------------------------------
# Resolve node IP and flannel interface from K3S_SUBNET when a specific subnet
# CIDR is provided. Sets LOCAL_IP and FLANNEL_IFACE in the caller's scope.
# Used by both server and agent install functions.

resolve_flannel_params() {
  if [[ "${K3S_SUBNET}" != "default_route_table" ]]; then
    export LOCAL_IP
    export FLANNEL_IFACE
    LOCAL_IP=$(ip -4 route ls "${K3S_SUBNET}" | grep -Po '(?<=src )(\S+)')
    FLANNEL_IFACE=$(ip -4 route ls "${K3S_SUBNET}" | grep -Po '(?<=dev )(\S+)')
    if [[ -z "${LOCAL_IP}" || -z "${FLANNEL_IFACE}" ]]; then
      echo "ERROR: resolve_flannel_params: could not determine LOCAL_IP or FLANNEL_IFACE from subnet '${K3S_SUBNET}'."
      echo "  'ip -4 route ls ${K3S_SUBNET}' returned no usable result."
      echo "  Check that K3S_SUBNET matches an interface route on this node."
      exit 1
    fi
  fi
}
